# Server settings (ServerProperties)
server:
  port: 8761
#  port: 8771
#  port: 8781

# Application
spring:
  application:
    name: eureka-server
#  profiles:
#    active: peer1
#    active: peer2
#    active: peer3

# Eureka
eureka:
  # 服务器
  server:
    # 关闭自我保护模式
    enable-self-preservation: false
    # 启用主动失效，并且每次主动失效检测间隔，默认为0
    eviction-interval-timer-in-ms: 1000
    # eureka server刷新readCacheMap间隔，决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上，默认为0
    response-cache-update-interval-ms: 1000
#    renewal-percent-threshold: 0.85 #default value
  # 服务提供方
  instance:
    hostname: peer1
#    hostname: peer2
#    hostname: peer3
    # 以IP将本实例注册到注册中心
    prefer-ip-address: true
    # Eureka Server的注册表Status显示内容格式
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://${eureka.instance.instance-id}
    # 服务心跳时间间隔，默认为30
    lease-renewal-interval-in-seconds: 1
    # 服务过期时间，超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除，默认为90
    # EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效
    lease-expiration-duration-in-seconds: 3
  # 服务调用方
  client:
    # 是否将本实例注册到注册中心 default: true
#    register-with-eureka: false
    # 是否从注册中心取注册列表 default: true
#    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://peer2:8771/eureka/,http://peer3:8781/eureka/
#      defaultZone: http://peer3:8781/eureka/,http://peer1:8761/eureka/
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8771/eureka/
